security:
    encoders:
        TmBundle\Entity\User:
            algorithm: bcrypt
    role_hierarchy:
        ROLE_EDITOR:    ROLE_USER
        ROLE_ADMIN:       [ROLE_EDITOR, ROLE_USER]
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_EDITOR, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]
    providers:
        task_manager:
            entity: 
                class: TmBundle:User
                property: username
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        task_manager_security: 
            switch_user: true
            pattern:    ^/  
            anonymous: ~
            form_login:
                check_path: _login_check
                login_path: login_tm
                success_handler: authentication_handler
                failure_handler: authentication_handler
                default_target_path: user_profil_tm
                username_parameter: login[username]
                password_parameter: login[password]
            logout:
                path:   _logout
                target: app_start_tm
            remember_me:
                secret:      '%secret%'
                lifetime: 31536000 
                path:     /
                domain:   ~
                remember_me_parameter: login[remember_me]
    access_control:
          - { path: ^/user-account, roles: ROLE_USER }

