parameters:
#    parameter_name: value

services:
    authentication_handler:
        class: TmBundle\Authentication\AuthenticationHandler
        public: false
        arguments: ["@router", "@session"]
    user_mailer:
        class: TmBundle\Mailer\UserMailer
        arguments: ["@mailer", "%mailer_sender%", "task_manager"]
    user_manager:
        class: TmBundle\Manager\UserManager
        arguments: ["@doctrine", "@router", "@templating", "@security.encoder_factory", "@user_mailer"]
    markdown:
        class: TmBundle\Utils\Markdown
    app.twig.markdown_to_html:
        class:     TmBundle\Twig\MarkdownToHTML
        arguments: ['@markdown']
        public:    false
        tags:
            - { name: twig.extension }
