parameters:
#    parameter_name: value

services:
    authentication_handler:
        class: AppBundle\Authentication\AuthenticationHandler
        public: false
        arguments: ["@router", "@session"]
    user_mailer:
        class: AppBundle\Mailer\UserMailer
        arguments: ["@mailer", "andrej.pakula@gmail.com", "task_manager"]
    user_manager:
        class: AppBundle\Manager\UserManager
        arguments: ["@doctrine", "@router", "@templating", "@security.encoder_factory", "@user_mailer"]
    markdown:
        class: AppBundle\Utils\Markdown
    app.twig.markdown_to_html:
        class:     AppBundle\Twig\MarkdownToHTML
        arguments: ['@markdown']
        public:    false
        tags:
            - { name: twig.extension }
